### ISSUE TITLE
Problem with Drive and Atributes

### ISSUE THREAD

**Issue by leandropug** [ceriath/candelafvtt#3] opened 2023-12-02 10:23 UTC
Hello, first, thanks for creating this system for Foundry.

I can't change the max value of drives and attributes, as I assume the first box where you can put a number is not the max drive for exemple, because when I put any number in the box nor the other drive number change ou my resistance change.

**Comment by ceriath** [comment] 2023-12-02 17:28
Hi!
Thanks for using the system and reporting this!
So generally that is by design, because Drives (and resistances) are defined by Roles/Specialties. Those values should change, when you drag and drop a Role and a Specialty on your character sheet.
If that does not resolve the problem, I'll need to take another look into it.

**Comment by Whirlmeister** [comment] 2023-12-08 00:42
This isnt the case. As per page 26 of the rules:
> Your character starts with 3 points in drives that are already determined by their role and specialty. These are represented by the filled-in notches below each drive point.

Then one paragraph later
>  Next, distribute 6 additional points in drives however you’d like, in a way that best reflects the kind of character you want to play

So we NEED to be able to alter the max value of drives.

**Comment by ceriath** [comment] 2023-12-08 00:47
Hi @Whirlmeister 
yes, you are absolutely correct, thank you for the clarification!
I must have confused it with action ratings while reading.
I'll get it fixed asap!

**Comment by ceriath** [comment] 2023-12-08 01:25
This has now been fixed with version 0.0.4, drives are now editable via character sheet

**Closed by ceriath** 2023-12-08 01:25 UTC
Labels: bug
